In [1]:
print(123)

123


print(123)

### 广播机制

#### 一维数组广播

In [3]:
[0,1,2,3] * 3

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

In [9]:
import numpy as np
# sort 排序
# [0,1,2,3]*3
arr1 = np.sort(np.array([0,1,2,3]*3)).reshape(4,3) #shape(4,3)
display(arr1)
arr2 = np.array([1,2,3]) # shape(3,)
display(arr2)
arr3 = arr1 + arr2 # arr2进行广播复制4份 shape(4,3)
arr3 # jupyter会将变量输出【Pycharm没有这样操作】

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([1, 2, 3])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [5]:
display(arr2)

array([1, 2, 3])

#### 二维数组广播

In [13]:
import numpy as np
arr1 = np.sort(np.array([0,1,2,3]*3)).reshape(4,3) # shape(4,3)
# arr2，二维
arr2 = np.array([[1],[2],[3],[4]]) # shape(4,1)
display(arr1,arr2)
arr3 = arr1 + arr2 # arr2 进行广播复制3份 shape(4,3)
display(arr1,arr2,arr3)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([[1],
       [2],
       [3],
       [4]])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([[1],
       [2],
       [3],
       [4]])

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

#### 高维数组广播

In [26]:
import numpy as np
arr1 = np.array([0,1,2,3,4,5,6,7]*3).reshape(3,4,2) #shape(3,4,2)
# arr2 = np.array([0,1,2,3,4,5,6,7]).reshape(4,2) #shape(4,2)
# arr2 = np.random.randint(0,10,size = (3,4,1))
arr2 = np.random.randint(0,10,size = (3,1,2))
display(arr1.shape,arr2.shape)
arr3 = arr1 + arr2 # arr2数组在0维上复制3份 shape(3,4,2)
arr3


(3, 4, 2)

(3, 1, 2)

array([[[ 9,  8],
        [11, 10],
        [13, 12],
        [15, 14]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]]])

### 通用函数

#### 元素级数字函数

abs、sqrt、square、exp、log、sin、cos、tan，maxinmum、minimum、all、any、inner、clip、round、trace、ceil、floor

In [27]:
import numpy as np
arr1 = np.array([1,4,8,9,16,25])
print(np.sqrt(arr1)) # 开平方
print(np.square(arr1)) # 平方
print(np.clip(arr1,2,16)) # 输出 array([ 2,  4,  8,  9, 16, 16])

[1.         2.         2.82842712 3.         4.         5.        ]
[  1  16  64  81 256 625]
[ 2  4  8  9 16 16]


In [28]:
# 以自然底数为底，进行的幂运算
np.exp(np.array([1,2,3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [31]:
np.e**3

20.085536923187664

In [32]:
x = np.array([1,5,2,9,3,6,8])
y = np.array([2,4,3,7,1,9,0])
print(np.maximum(x,y)) # 返回两个数组中的比较大的值

[2 5 3 9 3 9 8]


In [33]:
arr2 = np.random.randint(0,10,size = (5,5))
np.inner(arr2[0],arr2) #返回一维数组向量内积

array([ 99, 109, 138,  68,  55])

In [35]:
display(arr2,arr2[0])

array([[1, 6, 2, 7, 3],
       [9, 5, 2, 9, 1],
       [8, 8, 5, 9, 3],
       [8, 2, 5, 2, 8],
       [3, 0, 1, 5, 5]])

array([1, 6, 2, 7, 3])

In [39]:
for i in range(5):
    print((arr2[0] * arr2[i]).sum())

99
109
138
68
55


#### where函数使用


In [42]:
import numpy as np
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
cond = np.array([True,False,True,True,False])
np.where(cond,arr1,arr2) # True选择arr1，False选择arr2的值
# 输出 array([ 1,  4,  5,  7, 10])

array([ 1,  4,  5,  7, 10])

In [43]:
arr3 = np.random.randint(0,30,size = 20)
display(arr3)
np.where(arr3 < 15,arr3,-15) # 小于15还是自身的值，大于15设置成-15

array([ 9,  0,  6, 15, 26,  1, 28, 23, 19, 21, 25, 20, 27,  0, 27, 19, 15,
       12,  0, 24])

array([  9,   0,   6, -15, -15,   1, -15, -15, -15, -15, -15, -15, -15,
         0, -15, -15, -15,  12,   0, -15])

#### 排序方法

In [46]:
import numpy as np
arr = np.array([9,3,11,6,17,5,4,15,1])
display(arr)
arr.sort() # 直接改变原数组
arr

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

In [49]:
arr = np.array([9,3,11,6,17,5,4,15,1])
arr2 = np.sort(arr) # 返回深拷贝排序结果
arr2

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

In [48]:
arr # 原数据不变

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

In [51]:
arr = np.array([9,3,11,6,17,5,4,15,1])
index = arr.argsort() # 返回从小到大排序索引 array([8, 1, 6, 5, 3, 0, 2, 7, 4])
display(arr,index)
# 根据索引来排序
arr[index]

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

array([8, 1, 6, 5, 3, 0, 2, 7, 4], dtype=int64)

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

#### 集合运算

In [52]:
A = np.array([2,4,6,8])
B = np.array([3,4,5,6])
print(np.intersect1d(A,B)) # 交集 array([4, 6])
print(np.union1d(A,B)) # 并集 array([2, 3, 4, 5, 6, 8])
print(np.setdiff1d(A,B)) #差集，A中有，B中没有 array([2, 8])


[4 6]
[2 3 4 5 6 8]
[2 8]


#### 数学和统计函数

min、max、mean、median、sum、std、var、cumsum、cumprod、argmin、argmax、argwhere、cov、corrcoef

In [55]:
import numpy as np
arr1 = np.array([1,7,2,19,23,0,88,11,6,11])
print(arr1.min()) # 计算最小值 0
index = arr1.argmin()
arr1[index]

0


0

In [56]:
arr1.argmax() # 计算最大值的索引 返回 6

6

In [58]:
index = np.argwhere(arr1 > 20) # 返回大于20的元素的索引
arr1[index]

array([[23],
       [88]])

In [59]:
np.cumsum(arr1) # 计算累加和

array([  1,   8,  10,  29,  52,  52, 140, 151, 157, 168])

In [61]:
arr2 = np.random.randint(0,10,size = (4,5))
display(arr2)
arr2.mean() # 计算列的平均值

array([[6, 4, 4, 1, 9],
       [1, 7, 2, 5, 1],
       [3, 2, 0, 3, 8],
       [4, 6, 1, 5, 2]])

3.7

In [63]:
arr2_mean = arr2.mean(axis = 0) # 到底计算的是行，还是列？
display(arr2_mean,arr2_mean.shape)

array([3.5 , 4.75, 1.75, 3.5 , 5.  ])

(5,)

In [64]:
arr2_mean = arr2.mean(axis = 1) # 到底计算的是行，还是列？
display(arr2_mean,arr2_mean.shape)

array([4.8, 3.2, 3.2, 3.6])

(4,)

In [65]:
np.var(arr2) # 方差

6.210000000000001

In [68]:
((arr2 - arr2.mean())**2).mean()

6.210000000000001

In [73]:
arr2

array([[6, 4, 4, 1, 9],
       [1, 7, 2, 5, 1],
       [3, 2, 0, 3, 8],
       [4, 6, 1, 5, 2]])

In [72]:
np.cov(arr2,rowvar=True)

array([[ 8.7 , -5.2 ,  6.05, -2.85],
       [-5.2 ,  7.2 , -2.8 ,  4.35],
       [ 6.05, -2.8 ,  8.7 , -0.65],
       [-2.85,  4.35, -0.65,  4.3 ]])

In [81]:
np.cov(arr2[0],ddof=0) # 协方差

array(6.96)

In [88]:
np.round(((arr2[0] - arr2[0].mean())**2),2).sum()/5 # 方差
# 方差有两种计算公式！！！

6.959999999999999

In [87]:
((arr2[0] - arr2[0].mean())**2).sum()/(5-1)

8.7

In [71]:
np.cov(arr2,rowvar=False) # 协方差矩阵

array([[ 4.33333333, -1.83333333,  1.83333333, -3.        ,  5.66666667],
       [-1.83333333,  4.91666667,  0.91666667,  2.83333333, -8.        ],
       [ 1.83333333,  0.91666667,  2.91666667, -1.83333333,  1.66666667],
       [-3.        ,  2.83333333, -1.83333333,  3.66666667, -7.33333333],
       [ 5.66666667, -8.        ,  1.66666667, -7.33333333, 16.66666667]])

In [70]:
# 范围-1 到 1
np.corrcoef(arr2,rowvar=True) # 相关性系数

array([[ 1.        , -0.6570183 ,  0.6954023 , -0.46596254],
       [-0.6570183 ,  1.        , -0.35377909,  0.78178761],
       [ 0.6954023 , -0.35377909,  1.        , -0.10627216],
       [-0.46596254,  0.78178761, -0.10627216,  1.        ]])

### 线性代数

In [89]:
#矩阵的乘积
A = np.array([[4,2,3],
              [1,3,1]]) # shape(2,3)
B = np.array([[2,7],
              [-5,-7],
              [9,3]]) # shape(3,2)
np.dot(A,B) # 矩阵运算 A的最后一维和B的第一维必须一致

array([[ 25,  23],
       [ -4, -11]])

In [90]:
A @ B # 符号 @ 表示矩阵乘积运算

array([[ 25,  23],
       [ -4, -11]])

In [94]:
A = np.random.randint(0,10,size = (3,6))
B = np.random.randint(0,10,size = (6,7))
A.dot(B).shape

(3, 7)

In [97]:
np.set_printoptions(suppress=True)

In [102]:
#计算矩阵的逆
from numpy.linalg import inv,det,eig,qr,svd
A = np.array([[1,2,3],
              [2,3,4],
              [4,5,8]]) # shape(3,3)
B = inv(A) # 逆矩阵
display(B)
display(A @ B)
det(A)#计算矩阵行列式

array([[-2. ,  0.5,  0.5],
       [ 0. ,  2. , -1. ],
       [ 1. , -1.5,  0.5]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

-2.0000000000000004

### 作业维度

In [107]:
import numpy as np

arr = np.random.randint(0,10,size = (2,3,4,5))
display(arr.shape)
# 最后两维的和，指定轴即可
arr.sum(axis = (0,-1)).shape

(2, 3, 4, 5)

(3, 4)