### 最大值最小值归一化

In [16]:
import numpy as np

X_1 = np.random.randint(1,10,size = 10)
X_2 = np.random.randint(100,300,size =10)

X = np.c_[X_1,X_2]
X

array([[  5, 141],
       [  2, 221],
       [  6, 141],
       [  8, 193],
       [  4, 237],
       [  1, 145],
       [  3, 218],
       [  1, 116],
       [  4, 244],
       [  3, 275]])

In [17]:
X.min(axis = 0)

array([  1, 116])

In [18]:
(X - X.min(axis = 0))/(X.max(axis = 0) - X.min(axis = 0))

array([[0.57142857, 0.1572327 ],
       [0.14285714, 0.66037736],
       [0.71428571, 0.1572327 ],
       [1.        , 0.48427673],
       [0.42857143, 0.76100629],
       [0.        , 0.18238994],
       [0.28571429, 0.64150943],
       [0.        , 0.        ],
       [0.42857143, 0.80503145],
       [0.28571429, 1.        ]])

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit_transform(X)

array([[0.57142857, 0.1572327 ],
       [0.14285714, 0.66037736],
       [0.71428571, 0.1572327 ],
       [1.        , 0.48427673],
       [0.42857143, 0.76100629],
       [0.        , 0.18238994],
       [0.28571429, 0.64150943],
       [0.        , 0.        ],
       [0.42857143, 0.80503145],
       [0.28571429, 1.        ]])

In [22]:
X[-1,-1] *= 1000
X

array([[     5,    141],
       [     2,    221],
       [     6,    141],
       [     8,    193],
       [     4,    237],
       [     1,    145],
       [     3,    218],
       [     1,    116],
       [     4,    244],
       [     3, 275000]])

In [23]:
scaler.fit_transform(X)

array([[5.71428571e-01, 9.09474542e-05],
       [1.42857143e-01, 3.81979308e-04],
       [7.14285714e-01, 9.09474542e-05],
       [1.00000000e+00, 2.80118159e-04],
       [4.28571429e-01, 4.40185678e-04],
       [0.00000000e+00, 1.05499047e-04],
       [2.85714286e-01, 3.71065613e-04],
       [0.00000000e+00, 0.00000000e+00],
       [4.28571429e-01, 4.65650965e-04],
       [2.85714286e-01, 1.00000000e+00]])

### Z-score标准化【正态分布】

In [10]:
X_1 = np.random.randint(1,10,size = 10)
X_2 = np.random.randint(100,300,size =10)

X = np.c_[X_1,X_2]
X

array([[  1, 135],
       [  7, 200],
       [  3, 242],
       [  4, 208],
       [  8, 133],
       [  4, 103],
       [  4, 188],
       [  6, 263],
       [  5, 274],
       [  1, 120]])

In [12]:
X2 = (X - X.mean(axis = 0))/X.std(axis =0)
X2

array([[-1.50467048, -0.88305948],
       [ 1.23109403,  0.22932165],
       [-0.59274898,  0.948091  ],
       [-0.13678823,  0.3662301 ],
       [ 1.68705478, -0.9172866 ],
       [-0.13678823, -1.43069327],
       [-0.13678823,  0.02395898],
       [ 0.77513328,  1.30747567],
       [ 0.31917253,  1.49572478],
       [-1.50467048, -1.13976282]])

In [13]:
X2.mean(axis = 0)

array([8.8817842e-17, 8.8817842e-17])

In [14]:
X2.std(axis = 0)

array([1., 1.])

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# 模仿
scaler.fit(X) # 统一【模型，fit】，fit“训练”

scaler.transform(X) # 根据训练，得到平均值，标准差【transform 相当于 predict】

array([[ 0.61904762, -0.33385485],
       [-0.80952381, -0.3328845 ],
       [ 1.0952381 , -0.33385485],
       [ 2.04761905, -0.33322412],
       [ 0.14285714, -0.33269043],
       [-1.28571429, -0.33380633],
       [-0.33333333, -0.33292089],
       [-1.28571429, -0.33415808],
       [ 0.14285714, -0.33260553],
       [-0.33333333,  2.99999958]])

数据训练数据X_train又有测试数据X_test

scaler.fit(X_train) # 基准，先进行训练

数据转换：  
scaler.transform(X_train)  
scaler.transform(X_test)