### 基本操作

#### 创建

In [4]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [6]:
arr2 = np.random.randint(0,100,size = (10))
arr2

array([21, 33, 12, 76, 88, 35, 85, 63, 87, 74])

In [7]:
arr3 = np.random.randn(10)
arr3

array([-0.17581686, -1.43955515,  0.37722536,  0.7823387 ,  0.3417816 ,
       -0.80531385, -0.56203728,  0.98953924,  0.19044429, -1.03419931])

In [8]:
np.random.randint(-50,50,size = (5,3))

array([[ 29,  -5,  36],
       [ 23, -43, -34],
       [ 25,  -3,  29],
       [ 24,  -6, -12],
       [ 22, -26, -35]])

In [9]:
np.ones(shape = (5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros_like(arr3)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# 等差数列
arr1 = np.arange(0,10,3)
arr1

array([0, 3, 6, 9])

In [18]:
np.linspace(1,99,50)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [21]:
np.set_printoptions(suppress=True)

In [23]:
# 等比数列
np.logspace(1,10,num = 10,base = 2 )

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

#### 查看操作

In [33]:
arr = np.random.randint(0,100,size = (3,5,6,8))
arr

array([[[[64,  5, 83, 78, 95, 91, 63, 49],
         [58, 43, 29, 47, 10, 58, 80,  9],
         [28, 80, 62, 90, 62,  4, 92, 73],
         [86,  2, 55, 59, 45, 87, 65, 58],
         [53, 27, 80, 17, 76, 92, 47, 89],
         [20, 32, 77, 83, 46, 65, 81, 12]],

        [[16, 84, 30, 64, 40, 64,  5, 73],
         [12, 49, 75,  2, 23, 55, 27, 27],
         [19, 99, 58, 22, 53, 21, 68, 69],
         [ 8, 19,  7, 42, 67, 26, 86, 61],
         [99, 93, 80, 84, 98, 38, 53, 74],
         [ 4, 29, 33, 33, 77, 57, 43, 75]],

        [[91, 18, 98,  5, 54, 70, 97, 35],
         [96, 56, 21, 42, 77, 26, 95, 69],
         [15, 50, 35, 41, 57, 50, 35, 68],
         [74,  0, 63, 90, 80, 14, 32, 77],
         [41, 29, 64, 46,  8, 51, 34,  4],
         [63, 67, 21, 92, 28, 94, 92, 81]],

        [[27, 61, 88, 98, 41,  6, 81, 24],
         [99,  6, 15, 74, 30, 17, 79, 32],
         [53, 84, 12, 94, 53, 23,  4, 25],
         [82, 45, 27,  5, 46, 42, 32, 21],
         [27, 21, 71, 60,  2, 90, 80, 42],
     

In [34]:
arr.shape

(3, 5, 6, 8)

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr.size

720

In [37]:
3*5*6*8

720

In [38]:
arr.ndim

4

#### IO操作（文件）

In [39]:
arr1 = np.random.random(size = (3,5))
arr1

array([[0.76918382, 0.70337066, 0.1713871 , 0.47964993, 0.91068639],
       [0.73352993, 0.18642531, 0.34732269, 0.27737349, 0.76727313],
       [0.48569083, 0.44593777, 0.55092189, 0.68906946, 0.35782814]])

In [44]:
# 文件后缀，默认是npy
np.save(file = './arr1',arr = arr1)

In [45]:
np.load('./arr1.npy')

array([[0.76918382, 0.70337066, 0.1713871 , 0.47964993, 0.91068639],
       [0.73352993, 0.18642531, 0.34732269, 0.27737349, 0.76727313],
       [0.48569083, 0.44593777, 0.55092189, 0.68906946, 0.35782814]])

In [46]:
arr2 = np.logspace(1,10,num = 10,base =2)
arr2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [47]:
np.savez('./file2',arr_x = arr1,arr_y = arr2)

In [49]:
np.load('./file2.npz')['arr_x']

array([[0.76918382, 0.70337066, 0.1713871 , 0.47964993, 0.91068639],
       [0.73352993, 0.18642531, 0.34732269, 0.27737349, 0.76727313],
       [0.48569083, 0.44593777, 0.55092189, 0.68906946, 0.35782814]])

In [52]:
np.load('./file2.npz')['arr_y']

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [56]:
np.savetxt('./arr1.txt',arr1,delimiter=',',fmt = '%.5f')# f表示float浮点数

In [57]:
np.savetxt('./arr1.csv',arr1,delimiter=';',fmt = '%.5f')

In [58]:
np.savetxt('./arr2.csv',arr1,delimiter=',',fmt = '%.5f')