### 正规方程

#### 二元一次方程

$W = (X^TX)^{-1}X^Ty$

In [136]:
# 线性回归，到底是什么呢？
# 可以解决什么问题呢？
import numpy as np
X = np.array([[1,1],[2,-1]])
y = np.array([14,10])

# 正规方程使用 linalg 线性代数
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

array([8., 6.])

In [137]:
from sklearn.linear_model import LinearRegression # 线性回归

model = LinearRegression(fit_intercept=True) # 默认这个参数是True，一般情况下， 使用True
model.fit(X,y) # 建模，训练

# coef斜率，线性方程，系数 == 斜率，截距
# 上面的方程（求解方程的变量，系数，斜率 + 截距），有没有截距？
display(model.coef_, model.intercept_)

array([-0.8,  1.6])

13.2

In [138]:
# # 带截距
# # x + y = 14
# -0.8 + 1.6 + 13.2 = 14

# # 2x - y = 10
# 2*-0.8 - 1.6 + 13.2 = 10

#### 八元一次方程

In [139]:
# 上面八元一次方程对应的X数据
X = np.array([[  0 ,14 , 8 ,  0 ,  5,  -2,   9,  -3],
 [ -4 , 10 ,  6 ,  4 ,-14 , -2 ,-14  , 8],
 [ -1 , -6  , 5 ,-12 ,  3 , -3 ,  2 , -2],
 [  5 , -2  , 3 , 10  , 5 , 11 ,  4  ,-8],
 [-15 ,-15  ,-8 ,-15 ,  7 , -4, -12 ,  2],
 [ 11 ,-10 , -2 ,  4  , 3 , -9 , -6 ,  7],
 [-14 ,  0 ,  4 , -3  , 5 , 10 , 13 ,  7],
 [ -3 , -7 , -2 , -8  , 0 , -6 , -5 , -9]])
# 对应的y
y = np.array([ 339 ,-114  , 30 , 126, -395 , -87 , 422, -309])
display(X,y)

array([[  0,  14,   8,   0,   5,  -2,   9,  -3],
       [ -4,  10,   6,   4, -14,  -2, -14,   8],
       [ -1,  -6,   5, -12,   3,  -3,   2,  -2],
       [  5,  -2,   3,  10,   5,  11,   4,  -8],
       [-15, -15,  -8, -15,   7,  -4, -12,   2],
       [ 11, -10,  -2,   4,   3,  -9,  -6,   7],
       [-14,   0,   4,  -3,   5,  10,  13,   7],
       [ -3,  -7,  -2,  -8,   0,  -6,  -5,  -9]])

array([ 339, -114,   30,  126, -395,  -87,  422, -309])

In [140]:
# x1 到 x8分别是：1.,  5., 15.,  3.,  8.,  4., 17., 12.
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

In [141]:
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

0.0

#### 八元一次方程+截距【12】

In [142]:
y_new = y + 64
y_new

array([ 403,  -50,   94,  190, -331,  -23,  486, -245])

In [143]:
# 思考一个问题，增加了截距，相当于b ，未知数
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_new)
w

array([-9.53423295, -3.18237714, 32.89293368, 13.94370726, 12.88345187,
       -5.64066992, 14.95379584,  8.62431708])

In [144]:
X_new = np.concatenate([X,np.ones(shape =(8,1))],axis = 1)
X_new

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.]])

In [145]:
X_new.shape

(8, 9)

In [146]:
# 思考一个问题，增加了截距，相当于b ，未知数
w = np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T).dot(y_new)
w

array([ 31.7109375 ,  43.1328125 , -72.109375  ,  -8.6328125 ,
         6.4921875 ,  48.2265625 ,  12.44921875,  21.0546875 ,
       195.4375    ])

In [147]:
# 有唯一解，需要增加一行
# 构建方程，解
w = np.array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])
b = 64
X9 = np.random.randint(-10,10,size = 8) # x1 ~ x8【方程任意】
y9 = w.dot(X9) + b # 得到第 9个方程的目标值

# 合并数据
y_new = np.concatenate([y_new,[y9]])
y_new # 9个目标值了

array([ 403.,  -50.,   94.,  190., -331.,  -23.,  486., -245.,  116.])

In [148]:
# 执行一次
X_new = np.concatenate([X_new,[np.concatenate([X9,[1]])]])
X_new

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.],
       [  9.,  -5.,  -4.,   3.,   1.,  -2.,   7.,   0.,   1.]])

In [149]:
model = LinearRegression(fit_intercept=False)

model.fit(X_new,y_new)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])

0.0

In [150]:
model = LinearRegression(fit_intercept=True)

model.fit(X_new,y_new)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.,  0.])

63.99999999999997

In [151]:
### 思考一个问题，增加了截距，相当于b ，未知数
w = np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T).dot(y_new)
w

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])

他们正在讨论（X^TX)^-1X^TY为什么不能等于X^-1Y

$（X^TX)^{-1}X^TY$

$X^{-1}Y$

In [152]:
X

array([[  0,  14,   8,   0,   5,  -2,   9,  -3],
       [ -4,  10,   6,   4, -14,  -2, -14,   8],
       [ -1,  -6,   5, -12,   3,  -3,   2,  -2],
       [  5,  -2,   3,  10,   5,  11,   4,  -8],
       [-15, -15,  -8, -15,   7,  -4, -12,   2],
       [ 11, -10,  -2,   4,   3,  -9,  -6,   7],
       [-14,   0,   4,  -3,   5,  10,  13,   7],
       [ -3,  -7,  -2,  -8,   0,  -6,  -5,  -9]])

In [153]:
X.T

array([[  0,  -4,  -1,   5, -15,  11, -14,  -3],
       [ 14,  10,  -6,  -2, -15, -10,   0,  -7],
       [  8,   6,   5,   3,  -8,  -2,   4,  -2],
       [  0,   4, -12,  10, -15,   4,  -3,  -8],
       [  5, -14,   3,   5,   7,   3,   5,   0],
       [ -2,  -2,  -3,  11,  -4,  -9,  10,  -6],
       [  9, -14,   2,   4, -12,  -6,  13,  -5],
       [ -3,   8,  -2,  -8,   2,   7,   7,  -9]])

### 正规方程推导

In [158]:
theta = np.random.randint(0,10,size = 8)
theta

array([2, 5, 4, 8, 0, 3, 7, 0])

In [160]:
X = np.random.randint(0,10,size = 8)
X

array([4, 1, 3, 9, 5, 4, 6, 2])

In [161]:
y = X.dot(theta)
y

151

In [162]:
theta.dot(X)

151