### 概率的计算

#### 二分类

In [28]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X,y = datasets.load_iris(return_X_y=True)

cond = y != 2 # 将0和1筛选
X = X[cond]
y = y[cond]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.15)
display(X.shape,X_train.shape,X_test.shape,y)

(100, 4)

(85, 4)

(15, 4)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [30]:
y_ = model.predict(X_test)
print('算法预测：',y_)
print('真实结果：',y_test)

算法预测： [1 1 0 0 1 0 1 1 0 1 1 0 0 1 1]
真实结果： [1 1 0 0 1 0 1 1 0 1 1 0 0 1 1]


In [31]:
proba_ = model.predict_proba(X_test) # 算法计算的概率
proba_

array([[0.02206224, 0.97793776],
       [0.24120236, 0.75879764],
       [0.96237983, 0.03762017],
       [0.97188188, 0.02811812],
       [0.01665816, 0.98334184],
       [0.98649799, 0.01350201],
       [0.03895718, 0.96104282],
       [0.00149924, 0.99850076],
       [0.96723104, 0.03276896],
       [0.02303329, 0.97696671],
       [0.00634327, 0.99365673],
       [0.9782431 , 0.0217569 ],
       [0.98966935, 0.01033065],
       [0.01011837, 0.98988163],
       [0.00247129, 0.99752871]])

In [32]:
proba_.argmax(axis = 1) # 找到最大值的索引

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1], dtype=int64)

概率手动计算

In [33]:
w_ = model.coef_
b_ = model.intercept_
display(w_,b_)

array([[ 0.48053158, -0.81919705,  2.23165577,  0.88772266]])

array([-6.92808181])

和训练数据，进行多元线性回归的计算

In [34]:
X_test.shape

(15, 4)

In [35]:
w_.shape

(1, 4)

In [36]:
# 手动计算的！！！
z = X_test.dot(w_.T) + b_

def sigmoid(z):
    return 1/(1 + np.exp(-z))

# 自己算出来的概率，只有一列，默认情况下，计算的类别为1的概率
# 正样本，阳性。医院，清一色阴性，化验，
# negative ,阴性，0
# positive ，阳性，1 往往很多问题，都是关注阳性，所以，代码中返回的也是1，阳性【默认】
# 代码中，对1，特别关注
p = sigmoid(z) # 概率，就计算出来

np.concatenate([1- p,p],axis = 1) # 类别0 的概率

array([[0.02206224, 0.97793776],
       [0.24120236, 0.75879764],
       [0.96237983, 0.03762017],
       [0.97188188, 0.02811812],
       [0.01665816, 0.98334184],
       [0.98649799, 0.01350201],
       [0.03895718, 0.96104282],
       [0.00149924, 0.99850076],
       [0.96723104, 0.03276896],
       [0.02303329, 0.97696671],
       [0.00634327, 0.99365673],
       [0.9782431 , 0.0217569 ],
       [0.98966935, 0.01033065],
       [0.01011837, 0.98988163],
       [0.00247129, 0.99752871]])

#### 多分类-ovr

In [61]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X,y = datasets.load_iris(return_X_y=True)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.15)
display(X.shape,X_train.shape,X_test.shape,y)

(150, 4)

(127, 4)

(23, 4)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [62]:
model = LogisticRegression(multi_class='ovr')
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [63]:
y_ = model.predict(X_test)
display(y_,y_test)

array([0, 2, 1, 2, 0, 1, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 0, 0, 2, 0, 1, 0,
       1])

array([0, 2, 1, 2, 0, 1, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 0, 0, 2, 0, 1, 0,
       1])

In [64]:
np.set_printoptions(suppress=True)

In [65]:
proba_ = model.predict_proba(X_test)
proba_

array([[0.91694322, 0.08305604, 0.00000075],
       [0.00042777, 0.18254177, 0.81703046],
       [0.00576756, 0.74484365, 0.24938879],
       [0.00014637, 0.20010911, 0.79974452],
       [0.86199406, 0.1380031 , 0.00000284],
       [0.03333048, 0.91661764, 0.05005187],
       [0.07013132, 0.91571233, 0.01415635],
       [0.00050795, 0.26036414, 0.73912791],
       [0.00109884, 0.48661671, 0.51228445],
       [0.00053325, 0.19381465, 0.8056521 ],
       [0.93235633, 0.0676408 , 0.00000287],
       [0.00132297, 0.5777249 , 0.42095213],
       [0.00020874, 0.26356585, 0.73622541],
       [0.0198436 , 0.82651319, 0.15364321],
       [0.9025045 , 0.09749353, 0.00000197],
       [0.00007398, 0.41752696, 0.58239905],
       [0.89875152, 0.10124717, 0.0000013 ],
       [0.782686  , 0.21731141, 0.00000259],
       [0.00002734, 0.36004052, 0.63993214],
       [0.84295444, 0.15704422, 0.00000134],
       [0.01959694, 0.9431963 , 0.03720676],
       [0.95190054, 0.04809797, 0.00000149],
       [0.

In [68]:
proba_.argmax(axis = 1) # 根据概率，进行类别划分

array([0, 2, 1, 2, 0, 1, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 0, 0, 2, 0, 1, 0,
       1], dtype=int64)

计算3分类的概率

In [66]:
w_ = model.coef_
b_ = model.intercept_
display(w_,b_)

array([[-0.44140766,  0.8429343 , -2.26061786, -0.95927924],
       [-0.16500217, -1.90523912,  0.62421285, -1.05015866],
       [-0.37742822, -0.62239789,  2.81091994,  2.21761569]])

array([  6.66420345,   4.891154  , -13.30333644])

In [67]:
# 手动计算的！！！
z = X_test.dot(w_.T) + b_

def sigmoid(z):
    return 1/(1 + np.exp(-z))
# 自己算出来的概率，只有一列，默认情况下，计算的类别为1的概率
# 正样本，阳性。医院，清一色阴性，化验，
# negative ,阴性，0
# positive ，阳性，1 往往很多问题，都是关注阳性，所以，代码中返回的也是1，阳性【默认】
# 代码中，对1，特别关注
p = sigmoid(z) # 概率，就计算出来
p/(p.sum(axis = 1)).reshape(-1,1)

array([[0.91694322, 0.08305604, 0.00000075],
       [0.00042777, 0.18254177, 0.81703046],
       [0.00576756, 0.74484365, 0.24938879],
       [0.00014637, 0.20010911, 0.79974452],
       [0.86199406, 0.1380031 , 0.00000284],
       [0.03333048, 0.91661764, 0.05005187],
       [0.07013132, 0.91571233, 0.01415635],
       [0.00050795, 0.26036414, 0.73912791],
       [0.00109884, 0.48661671, 0.51228445],
       [0.00053325, 0.19381465, 0.8056521 ],
       [0.93235633, 0.0676408 , 0.00000287],
       [0.00132297, 0.5777249 , 0.42095213],
       [0.00020874, 0.26356585, 0.73622541],
       [0.0198436 , 0.82651319, 0.15364321],
       [0.9025045 , 0.09749353, 0.00000197],
       [0.00007398, 0.41752696, 0.58239905],
       [0.89875152, 0.10124717, 0.0000013 ],
       [0.782686  , 0.21731141, 0.00000259],
       [0.00002734, 0.36004052, 0.63993214],
       [0.84295444, 0.15704422, 0.00000134],
       [0.01959694, 0.9431963 , 0.03720676],
       [0.95190054, 0.04809797, 0.00000149],
       [0.

#### 多分类-multinomial

In [72]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X,y = datasets.load_iris(return_X_y=True)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.15)
display(X.shape,X_train.shape,X_test.shape,y)

(150, 4)

(127, 4)

(23, 4)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [73]:
model = LogisticRegression(multi_class='multinomial')
model.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial')

In [74]:
y_ = model.predict(X_test)
display(y_,y_test)

array([1, 2, 0, 2, 0, 1, 0, 2, 2, 1, 0, 0, 2, 0, 1, 0, 2, 1, 2, 2, 2, 2,
       1])

array([1, 1, 0, 2, 0, 1, 0, 2, 2, 2, 0, 0, 2, 0, 1, 0, 2, 2, 2, 2, 2, 2,
       1])

In [75]:
model.predict_proba(X_test)

array([[0.00146372, 0.78569121, 0.21284507],
       [0.00303043, 0.47467975, 0.52228982],
       [0.97507963, 0.02492032, 0.00000005],
       [0.00000668, 0.02268486, 0.97730846],
       [0.98722969, 0.01277029, 0.00000002],
       [0.00305499, 0.80907817, 0.18786684],
       [0.95575582, 0.044244  , 0.00000017],
       [0.00011553, 0.27712457, 0.7227599 ],
       [0.00148462, 0.49219112, 0.50632426],
       [0.00074413, 0.52535981, 0.47389606],
       [0.98777486, 0.01222513, 0.00000001],
       [0.97672157, 0.02327839, 0.00000004],
       [0.00000087, 0.00513241, 0.99486672],
       [0.9836172 , 0.01638278, 0.00000002],
       [0.0691592 , 0.92752786, 0.00331294],
       [0.96072438, 0.03927551, 0.00000011],
       [0.00001947, 0.0488904 , 0.95109013],
       [0.00836051, 0.67134604, 0.32029345],
       [0.00000689, 0.05087214, 0.94912097],
       [0.00001818, 0.02027107, 0.97971075],
       [0.00000006, 0.0052766 , 0.99472334],
       [0.00043294, 0.21908237, 0.78048469],
       [0.

手动计算概率，softmax函数

In [76]:
w_ = model.coef_
b_ = model.intercept_
display(w_,b_)

array([[-0.48188732,  0.83214485, -2.40480374, -1.03162956],
       [ 0.36069693, -0.41034759, -0.10676361, -0.97244217],
       [ 0.12119039, -0.42179726,  2.51156734,  2.00407173]])

array([ 10.17911193,   3.10064594, -13.27975787])

In [89]:
np.set_printoptions(suppress=True)
z = X_test.dot(w_.T) + b_

def softmax(z):
    return np.exp(z)/(np.exp(z).sum(axis = 1)).reshape(-1,1)

softmax(z)

array([[0.00146372, 0.78569121, 0.21284507],
       [0.00303043, 0.47467975, 0.52228982],
       [0.97507963, 0.02492032, 0.00000005],
       [0.00000668, 0.02268486, 0.97730846],
       [0.98722969, 0.01277029, 0.00000002],
       [0.00305499, 0.80907817, 0.18786684],
       [0.95575582, 0.044244  , 0.00000017],
       [0.00011553, 0.27712457, 0.7227599 ],
       [0.00148462, 0.49219112, 0.50632426],
       [0.00074413, 0.52535981, 0.47389606],
       [0.98777486, 0.01222513, 0.00000001],
       [0.97672157, 0.02327839, 0.00000004],
       [0.00000087, 0.00513241, 0.99486672],
       [0.9836172 , 0.01638278, 0.00000002],
       [0.0691592 , 0.92752786, 0.00331294],
       [0.96072438, 0.03927551, 0.00000011],
       [0.00001947, 0.0488904 , 0.95109013],
       [0.00836051, 0.67134604, 0.32029345],
       [0.00000689, 0.05087214, 0.94912097],
       [0.00001818, 0.02027107, 0.97971075],
       [0.00000006, 0.0052766 , 0.99472334],
       [0.00043294, 0.21908237, 0.78048469],
       [0.

In [90]:
A = np.random.randint(0,10,size = (5,3))
A

array([[0, 5, 5],
       [4, 2, 8],
       [2, 2, 7],
       [1, 7, 6],
       [9, 2, 6]])

In [93]:
A.sum(axis = 1)

array([10, 14, 11, 14, 17])